_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 105
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 105
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.7
            "8":
                - 2
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
activation:
    value: sigmoid
batch_size:
    value: 32
dataset:
    value: fashion_mnist
epochs:
    value: 5
hidden_size:
    value: 64
learning_rate:
    value: 0.0001
loss:
    value: cross_entropy
num_layers:
    value: 4
optimizer:
    value: sgd
weight_decay:
    value: 0.5
weight_init:
    value: random
