wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
dataset:
  value: fashion_mnist
dropout:
  value: 0
epochs:
  value: 10
hidden_size:
  value: 32
learning_rate:
  value: 0.1
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: momentum
weight_decay:
  value: 0
weight_init:
  value: random
