wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
dataset:
  value: fashion_mnist
epochs:
  value: 10
hidden_size:
  value: 32
learning_rate:
  value: 0.1
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: nag
weight_decay:
  value: 0.0005
weight_init:
  value: random
