wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 32
dataset:
  value: fashion_mnist
dropout:
  value: 0
epochs:
  value: 5
hidden_size:
  value: 64
learning_rate:
  value: 0.01
loss:
  value: cross_entropy
num_layers:
  value: 5
optimizer:
  value: momentum
weight_decay:
  value: 0.0005
weight_init:
  value: random
