wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
dataset:
  value: fashion_mnist
dropout:
  value: 0
epochs:
  value: 5
hidden_size:
  value: 32
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
num_layers:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0.0001
weight_init:
  value: Xavier
