_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 105
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 105
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.7
            "8":
                - 2
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
NAME:
    value: SIDDHANT BARANWAL
ROLL NO.:
    value: DA24M021
activation:
    value: sigmoid
batch_size:
    value: 128
dataset:
    value: fashion_mnist
dropout:
    value: 0
epochs:
    value: 5
hidden_size:
    value: 128
learning_rate:
    value: 0.1
loss:
    value: cross_entropy
num_layers:
    value: 5
optimizer:
    value: sgd
weight_decay:
    value: 0.0005
weight_init:
    value: random
