wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dataset:
  value: fashion_mnist
dropout:
  value: 0
epochs:
  value: 15
hidden_size:
  value: 32
learning_rate:
  value: 0.1
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: momentum
weight_decay:
  value: 0.0001
weight_init:
  value: Xavier
