wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
dataset:
  value: fashion_mnist
dropout:
  value: 0
epochs:
  value: 15
hidden_size:
  value: 64
learning_rate:
  value: 0.1
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: sgd
weight_decay:
  value: 0
weight_init:
  value: Xavier
