wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 64
dataset:
  value: fashion_mnist
dropout:
  value: 0
epochs:
  value: 10
hidden_size:
  value: 128
learning_rate:
  value: 0.1
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: nag
weight_init:
  value: random
